Problem statement
Boston dataset is one of the datasets available in sklearn.

You are given a Training dataset csv file with X train and Y train data. As studied in lecture, your task is to come up with Gradient Descent algorithm and thus predictions for the test dataset given.

Your task is to:

1. Code Gradient Descent for N features and come with predictions.
2. Try and test with various combinations of learning rates and number of iterations.
3. Try using Feature Scaling, and see if it helps you in getting better results. 
Read Instructions carefully -

1. Use Gradient Descent as a training algorithm and submit results predicted.
2. Files are in csv format, you can use genfromtxt function in numpy to load data from csv file. Similarly you can use savetxt function to save data into a file.
3. Submit a csv file with only predictions for X test data. File name should not have spaces. File should not have any headers and should only have one column i.e. predictions. Also predictions shouldn't be in exponential form. 
4. Your score is based on coefficient of determination.

In [149]:
import numpy as np

In [150]:
train_data=np.loadtxt('train.csv', delimiter=',')

In [151]:
def run():
  learning_rate=0.0001
  num_iterations=1000
  m, c=gd(np.array(train_data), learning_rate, num_iterations)
  return m,c

In [152]:
def step_gradient(points, learning_rate, m, c):
  m_slope=[0 for i in range(len(points[0, 0:-1]))]
  c_slope=0
  M=len(points)
  N=len(points[0, 0:-1]) 
  for i in range(M):
    for j in range(N):
      x=points[i][j]
      y=points[i][-1]
      m_slope[j]+=-2*x*(y-m[j]*x-c)/M
      c_slope+=-2*(y-m[j]*x-c)/M
  m_slope=np.array(m_slope)
  m=np.array(m)
  new_m=m-learning_rate*m_slope
  new_c=c-learning_rate*c_slope
  return new_m, new_c

In [153]:
def cost(points, m, c):
  total_cost=0
  M=len(points)
  N=len(points[0, 0:-1])
  for i in range(M):
    for j in range(N):
      x=points[i][j]
      y=points[i][-1]
      total_cost+=(1/M)*((y-m[j]*x-c)**2)
  return total_cost

In [154]:
def gd(points, learning_rate, num_iterations):
  m=[0 for i in range(len(points[0, 0:-1]))]
  c=0
  for i in range(num_iterations):
    m,c=step_gradient(points, learning_rate, m, c)
    print("cost: ", cost(points, m, c))
  return m, c

In [155]:
m, c=run()

cost:  7753.999284356072
cost:  7719.588274020082
cost:  7685.355537141659
cost:  7651.300148022438
cost:  7617.421185771633
cost:  7583.717734281127
cost:  7550.188882200654
cost:  7516.833722913019
cost:  7483.6513545095995
cost:  7450.640879765792
cost:  7417.8014061167805
cost:  7385.132045633236
cost:  7352.631914997435
cost:  7320.300135478989
cost:  7288.1358329113555
cost:  7256.138137667923
cost:  7224.306184638455
cost:  7192.639113205773
cost:  7161.136067222194
cost:  7129.796194986543
cost:  7098.618649220945
cost:  7067.602587047847
cost:  7036.747169967171
cost:  7006.051563833662
cost:  6975.514938834143
cost:  6945.136469465045
cost:  6914.915334510153
cost:  6884.850717018146
cost:  6854.941804280611
cost:  6825.187787809938
cost:  6795.587863317332
cost:  6766.141230691164
cost:  6736.847093975087
cost:  6707.704661346668
cost:  6678.713145095706
cost:  6649.871761603017
cost:  6621.179731319166
cost:  6592.636278743211
cost:  6564.240632401918
cost:  6535.9920248286

In [156]:
test_data=np.loadtxt('test.csv', delimiter=',')    

In [157]:
def predictions(test_data):
    return m*test_data+c

In [158]:
predictions(test_data)

array([[19.09537349, 20.67956857, 20.1470243 , ..., 20.28648915,
        20.07163626, 19.63712176],
       [21.1978051 , 20.67956857, 20.62452917, ..., 21.86584241,
        21.18289254, 22.06435249],
       [21.20399967, 20.67956857, 20.85185804, ..., 19.98565995,
        21.18289254, 21.57046992],
       ...,
       [21.20199721, 22.0676996 , 22.02163073, ..., 21.00095848,
        21.15557882, 21.79719893],
       [21.19766876, 20.67956857, 21.23683207, ..., 20.0232636 ,
        21.12784672, 20.68991771],
       [21.02701323, 20.67956857, 19.9779556 , ..., 22.35468985,
        19.34044122, 20.32961192]])

In [177]:
#Experimenting with different values of learning_rate and num_iterations
def run2():
  learning_rate=0.01
  num_iterations=1000
  m, c=gd(np.array(train_data), learning_rate, num_iterations)
  return m,c

In [181]:
m, c=run2()

cost:  4774.253221935107
cost:  3119.901852400978
cost:  2210.3957328067663
cost:  1708.894329738277
cost:  1430.9466503274705
cost:  1275.5464524878055
cost:  1187.3798797338338
cost:  1136.1532485073974
cost:  1105.2734786117217
cost:  1085.6497856355618
cost:  1072.2996422338986
cost:  1062.4902836911585
cost:  1054.7210375127172
cost:  1048.1660664743051
cost:  1042.369222283721
cost:  1037.076948677576
cost:  1032.1467770377044
cost:  1027.4972147501974
cost:  1023.0802993969714
cost:  1018.8665644055376
cost:  1014.8368011211652
cost:  1010.9775426457878
cost:  1007.2785858338735
cost:  1003.7316295359051
cost:  1000.3295242679709
cost:  997.0658568720609
cost:  993.9347187908608
cost:  990.9305750597877
cost:  988.0481886168702
cost:  985.2825750641424
cost:  982.628974257719
cost:  980.0828312609525
cost:  977.6397825664806
cost:  975.2956453396674
cost:  973.0464084471141
cost:  970.8882245879523
cost:  968.8174031492754
cost:  966.8304035734311
cost:  964.9238291161861
cost: 

In [182]:
predictions(test_data)

array([[13.19947587, 21.22894426, 18.13636766, ..., 18.92603922,
        17.80045685, 15.50632177],
       [23.98044855, 21.22894426, 20.8585757 , ..., 27.94278621,
        24.01583477, 28.82892114],
       [24.01221346, 21.22894426, 22.15455514, ..., 17.20856357,
        24.01583477, 26.11809534],
       ...,
       [24.00194514, 28.84372375, 28.82331363, ..., 23.00504378,
        23.8630661 , 27.36256697],
       [23.97974942, 21.22894426, 24.349254  , ..., 17.42324803,
        23.70795745, 21.28491484],
       [23.10465194, 21.22894426, 17.17252367, ..., 30.73368409,
        13.71080303, 19.30726609]])

In [187]:
#Applying feature scaling
from sklearn import preprocessing
ss=preprocessing.StandardScaler()
ss.fit(train_data[:,:-1])
train_data_transformed=ss.transform(train_data[:,:-1])

In [190]:
def run3():
  learning_rate=0.01
  num_iterations=1000
  m, c=gd2(np.array(train_data), learning_rate, num_iterations)
  return m,c

In [194]:
def gd2(points, learning_rate, num_iterations):
  m=[0 for i in range(len(points[0, 0:-1]))]
  c=0
  for i in range(num_iterations):
    m,c=step_gradient2(points, learning_rate, m, c)
    print("cost: ", cost2(points, m, c))
  return m, c

In [196]:
def cost2(points, m, c):
  total_cost=0
  M=len(points)
  N=len(points[0, 0:-1])
  for i in range(M):
    for j in range(N):
      x=train_data_transformed[i][j]
      y=points[i][-1]
      total_cost+=(1/M)*((y-m[j]*x-c)**2)
  return total_cost

In [198]:
def step_gradient2(points, learning_rate, m, c):
  m_slope=[0 for i in range(len(points[0, 0:-1]))]
  c_slope=0
  M=len(points)
  N=len(points[0, 0:-1]) 
  for i in range(M):
    for j in range(N):
      x=train_data_transformed[i][j]
      y=points[i][-1]
      m_slope[j]+=-2*x*(y-m[j]*x-c)/M
      c_slope+=-2*(y-m[j]*x-c)/M
  m_slope=np.array(m_slope)
  m=np.array(m)
  new_m=m-learning_rate*m_slope
  new_c=c-learning_rate*c_slope
  return new_m, new_c

In [199]:
m, c=run3()

cost:  4773.328313128895
cost:  3118.516395383328
cost:  2208.8312304329816
cost:  1707.316477601502
cost:  1429.4493402438736
cost:  1274.1798484045632
cost:  1186.167961368977
cost:  1135.1045967307753
cost:  1104.3878179471603
cost:  1084.921906997706
cost:  1071.7217292285825
cost:  1062.0532764883665
cost:  1054.415421775571
cost:  1047.982321578286
cost:  1042.2980691475752
cost:  1037.1094806296385
cost:  1032.2745229890681
cost:  1027.7121636050283
cost:  1023.3749025948473
cost:  1019.2337264094388
cost:  1015.2698635195022
cost:  1011.4702651206811
cost:  1007.8251258455657
cost:  1004.3265217625984
cost:  1000.9676603731574
cost:  997.7424659041211
cost:  994.6453483667884
cost:  991.6710733986912
cost:  988.8146874403342
cost:  986.0714733539382
cost:  983.4369228472075
cost:  980.9067182290283
cost:  978.4767193999462
cost:  976.1429538286662
cost:  973.9016082785729
cost:  971.7490216028034
cost:  969.6816782303722
cost:  967.6962021324398
cost:  965.7893511491591
cost:  

In [202]:
test_data_transformed=ss.transform(test_data)
predictions(test_data_transformed)

array([[13.20144154, 21.15996215, 18.23274201, ..., 18.95321369,
        17.7872707 , 15.57024875],
       [23.9825329 , 21.15996215, 20.95708217, ..., 27.97099254,
        24.00222607, 28.89510607],
       [24.01429815, 21.15996215, 22.25407667, ..., 17.2355415 ,
        24.00222607, 26.18382083],
       ...,
       [24.00402972, 28.77517773, 28.92805838, ..., 23.03268505,
        23.84946779, 27.42850338],
       [23.98183375, 21.15996215, 24.45049451, ..., 17.45025052,
        23.69436968, 21.3498212 ],
       [23.10672664, 21.15996215, 17.26814309, ..., 30.7622098 ,
        13.69789493, 19.37183727]])

In [224]:
import pandas as pd
ans=np.array(predictions(test_data_transformed))
ans=np.array(ans).reshape(-1)

In [232]:
predictions = [format(x, 'f') for x in ans]
pd.DataFrame(predictions, columns=["predictions"]).to_csv("predictions.csv", index=False)