Problem statement
Combined Cycle Power Plant dataset contains 9568 data points collected from a Combined Cycle Power Plant over 6 years (2006-2011), when the power plant was set to work with full load. Features consist of hourly average ambient variables Temperature (T), Ambient Pressure (AP), Relative Humidity (RH) and Exhaust Vacuum (V) to predict the net hourly electrical energy output (EP) of the plant.

You are given:

1. A Readme file for more details on dataset. 
2. A Training dataset csv file with X train and Y train data
3. A X test File and you have to predict and submit predictions for this file.
Your task is to:

1. Code Gradient Descent for N features and come with predictions.
2. Try and test with various combinations of learning rates and number of iterations.
3. Try using Feature Scaling, and see if it helps you in getting better results. 
Read Instructions carefully -

1. Use Gradient Descent as a training algorithm and submit results predicted.
2. Files are in csv format, you can use genfromtxt function in numpy to load data from csv file. Similarly you can use savetxt function to save data into a file.
3. Submit a csv file with only predictions for X test data. File should not have any headers and should only have one column i.e. predictions. Also predictions shouldn't be in exponential form.
4. Your score is based on coefficient of determination. So it can be possible that nobody gets full score.

In [2]:
import numpy as np

In [4]:
train_data=np.loadtxt('train.csv', delimiter=',')

In [5]:
def run():
  learning_rate=0.0001
  num_iterations=1000
  m, c=gd(np.array(train_data), learning_rate, num_iterations)
  return m,c

In [8]:
def step_gradient(points, learning_rate, m, c):
  m_slope=[0 for i in range(len(points[0, 0:-1]))]
  c_slope=0
  M=len(points)
  N=len(points[0, 0:-1]) 
  for i in range(M):
    for j in range(N):
      x=points[i][j]
      y=points[i][-1]
      m_slope[j]+=-2*x*(y-m[j]*x-c)/M
      c_slope+=-2*(y-m[j]*x-c)/M
  m_slope=np.array(m_slope)
  m=np.array(m)
  new_m=m-learning_rate*m_slope
  new_c=c-learning_rate*c_slope
  return new_m, new_c

In [9]:
def cost(points, m, c):
  total_cost=0
  M=len(points)
  N=len(points[0, 0:-1])
  for i in range(M):
    for j in range(N):
      x=points[i][j]
      y=points[i][-1]
      total_cost+=(1/M)*((y-m[j]*x-c)**2)
  return total_cost

In [10]:
def gd(points, learning_rate, num_iterations):
  m=[0 for i in range(len(points[0, 0:-1]))]
  c=0
  for i in range(num_iterations):
    m,c=step_gradient(points, learning_rate, m, c)
    print("cost: ", cost(points, m, c))
  return m, c

In [14]:
m, c=run()

cost:  8625320156.248014
cost:  360166459136531.0
cost:  1.5039826080894239e+19
cost:  6.280328523572409e+23
cost:  2.6225387283001753e+28
cost:  1.095119364474608e+33
cost:  4.572997948537643e+37
cost:  1.909591859639282e+42
cost:  7.974071082982394e+46
cost:  3.329811515246899e+51
cost:  1.3904622383838187e+56
cost:  5.806290318586697e+60
cost:  2.424589919314723e+65
cost:  1.0124599278176232e+70
cost:  4.2278287856828133e+74
cost:  1.7654561676913683e+79
cost:  7.372189457139742e+83
cost:  3.0784778680167615e+88
cost:  1.2855103682524564e+93
cost:  5.3680324424406494e+97
cost:  2.2415822551664485e+102
cost:  9.360396123834259e+106
cost:  3.90871293672296e+111
cost:  1.6321998150060933e+116
cost:  6.815737761347687e+120
cost:  2.8461148447826805e+125
cost:  1.188480248702211e+130
cost:  4.962854201562835e+134
cost:  2.072387980603095e+139
cost:  8.653874902869027e+143
cost:  3.61368390163805e+148
cost:  1.5090016307743849e+153
cost:  6.301286951658198e+157
cost:  2.6312905458408815e+

C:\Users\DELL\AppData\Local\Temp\ipykernel_18368\2880520143.py:9: RuntimeWarning: overflow encountered in scalar power
  total_cost+=(1/M)*((y-m[j]*x-c)**2)


cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf
cost:  inf


C:\Users\DELL\AppData\Local\Temp\ipykernel_18368\2593173474.py:10: RuntimeWarning: overflow encountered in scalar multiply
  m_slope[j]+=-2*x*(y-m[j]*x-c)/M
C:\Users\DELL\AppData\Local\Temp\ipykernel_18368\2593173474.py:14: RuntimeWarning: invalid value encountered in subtract
  new_m=m-learning_rate*m_slope


cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan
cost:  nan

In [15]:
test_data=np.loadtxt('test.csv', delimiter=',')    

In [16]:
def predictions(test_data):
    return m*test_data+c

In [20]:
predictions(test_data)

array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       ...,
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])

In [62]:
#Experimenting with different values of learning_rate and num_iterations
def run2():
  learning_rate=0.0000001
  num_iterations=10000
  m, c=gd(np.array(train_data), learning_rate, num_iterations)
  return m,c

In [63]:
m, c=run2()

cost:  750368.9381771116
cost:  701585.8106362603
cost:  670518.0694423226
cost:  650637.5790559598
cost:  637822.0020061926
cost:  629468.1955741999
cost:  623932.3463910788
cost:  620176.4309652637
cost:  617544.9653118714
cost:  615624.0285358846
cost:  614152.2401352302
cost:  612964.5446369144
cost:  611956.7131539657
cost:  611062.9271033014
cost:  610241.6229452902
cost:  609466.5535294076
cost:  608721.1435819726
cost:  607994.9253531826
cost:  607281.2878270997
cost:  606576.0554101729
cost:  605876.5904124342
cost:  605181.2262893325
cost:  604488.9097495724
cost:  603798.9747562372
cost:  603110.9998146893
cost:  602424.717853854
cost:  601739.9593187771
cost:  601056.6162350879
cost:  600374.6195167665
cost:  599693.9246365813
cost:  599014.5025773488
cost:  598336.334117974
cost:  597659.4062251835
cost:  596983.7097749619
cost:  596309.2381138228
cost:  595635.986150131
cost:  594963.9497804602
cost:  594293.1255271764
cost:  593623.5103097401
cost:  592955.1013001524
cos

In [66]:
predictions(test_data)

array([[140.45410407, 330.52662398, 456.40048213, 543.55032726],
       [141.85501179, 300.88563386, 454.20284029, 488.44824441],
       [315.10060015, 588.98351137, 451.05631847, 472.44893975],
       ...,
       [284.86434181, 520.44852364, 452.60048636, 549.52021706],
       [275.17473006, 336.56460345, 454.78022481, 390.84054618],
       [254.97831039, 473.55616361, 457.01814929, 508.74586973]])

In [68]:
#Applying feature scaling
from sklearn import preprocessing
ss=preprocessing.StandardScaler()
ss.fit(train_data[:,:-1])
train_data_transformed=ss.transform(train_data[:,:-1])

In [90]:
def run3():
  learning_rate=0.00001
  num_iterations=1000
  m, c=gd2(np.array(train_data), learning_rate, num_iterations)
  return m,c

In [91]:
def gd2(points, learning_rate, num_iterations):
  m=[0 for i in range(len(points[0, 0:-1]))]
  c=0
  for i in range(num_iterations):
    m,c=step_gradient2(points, learning_rate, m, c)
    print("cost: ", cost2(points, m, c))
  return m, c

In [92]:
def cost2(points, m, c):
  total_cost=0
  M=len(points)
  N=len(points[0, 0:-1])
  for i in range(M):
    for j in range(N):
      x=train_data_transformed[i][j]
      y=points[i][-1]
      total_cost+=(1/M)*((y-m[j]*x-c)**2)
  return total_cost

In [93]:
def step_gradient2(points, learning_rate, m, c):
  m_slope=[0 for i in range(len(points[0, 0:-1]))]
  c_slope=0
  M=len(points)
  N=len(points[0, 0:-1]) 
  for i in range(M):
    for j in range(N):
      x=train_data_transformed[i][j]
      y=points[i][-1]
      m_slope[j]+=-2*x*(y-m[j]*x-c)/M
      c_slope+=-2*(y-m[j]*x-c)/M
  m_slope=np.array(m_slope)
  m=np.array(m)
  new_m=m-learning_rate*m_slope
  new_c=c-learning_rate*c_slope
  return new_m, new_c

In [94]:
m, c=run3()

cost:  827073.2272853843
cost:  826941.0642959394
cost:  826808.9224487966
cost:  826676.8017405719
cost:  826544.7021678694
cost:  826412.6237273437
cost:  826280.5664155807
cost:  826148.5302292143
cost:  826016.5151648701
cost:  825884.5212191518
cost:  825752.5483886852
cost:  825620.5966701087
cost:  825488.6660600315
cost:  825356.7565550655
cost:  825224.8681518517
cost:  825093.0008470113
cost:  824961.15463717
cost:  824829.3295189459
cost:  824697.5254889631
cost:  824565.7425438586
cost:  824433.9806802504
cost:  824302.2398947648
cost:  824170.5201840312
cost:  824038.821544677
cost:  823907.1439733452
cost:  823775.4874666579
cost:  823643.8520212246
cost:  823512.2376336944
cost:  823380.6443006952
cost:  823249.0720188653
cost:  823117.5207848266
cost:  822985.9905952142
cost:  822854.481446676
cost:  822722.9933358154
cost:  822591.5262592899
cost:  822460.0802137255
cost:  822328.6551957662
cost:  822197.2512020231
cost:  822065.8682291774
cost:  821934.5062738273
cost

In [95]:
test_data_transformed=ss.transform(test_data)
predictions(test_data_transformed)

array([[35.27028478, 35.2233197 , 35.06734192, 35.1002692 ],
       [35.26511889, 35.31078441, 34.92214344, 35.01611923],
       [34.62627117, 34.46066445, 34.71425233, 34.99168565],
       ...,
       [34.73776818, 34.66289767, 34.8162757 , 35.10938621],
       [34.77349888, 35.20550281, 34.96029131, 34.86705617],
       [34.84797372, 34.80126776, 35.10815127, 35.04711705]])

In [96]:
import pandas as pd
ans=np.array(predictions(test_data_transformed))
ans=np.array(ans).reshape(-1)

In [97]:
predictions = [format(x, 'f') for x in ans]
pd.DataFrame(predictions, columns=["predictions"]).to_csv("predictions.csv", index=False)